'use client';
import { useMemo, useState } from 'react';

type Enquiry = { id: string; studentName: string; parentName: string; class: string; school: string; phone: string; email: string | null; subjects: string; message: string; status: 'new' | 'contacted' | 'enrolled' | 'closed'; notes: string; createdAt: string };
export default function AdminInbox({ initial }: { initial: Enquiry[] }) {
  const [items, setItems] = useState(initial);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const visible = useMemo(() => items.filter(item => (!status || item.status === status) && (!search || `${item.studentName} ${item.parentName} ${item.phone} ${item.email ?? ''}`.toLowerCase().includes(search.toLowerCase()))), [items, search, status]);
  async function update(id: string, data: { status?: string; notes?: string }) { const response = await fetch('/api/admin/enquiries', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id, ...data }) }); if (!response.ok) return; const updated = await response.json(); setItems(current => current.map(item => item.id === id ? updated : item)); }
  async function remove(id: string) { if (!window.confirm('Delete this enquiry permanently?')) return; const response = await fetch(`/api/admin/enquiries?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); if (response.ok) setItems(current => current.filter(item => item.id !== id)); }
  function exportCsv() { const header = ['Student', 'Parent', 'Class', 'School', 'Phone', 'Email', 'Subjects', 'Message', 'Status', 'Created']; const rows = visible.map(item => [item.studentName, item.parentName, item.class, item.school, item.phone, item.email ?? '', item.subjects, item.message, item.status, item.createdAt]); const csv = [header, ...rows].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'brilliant-minds-enquiries.csv'; link.click(); URL.revokeObjectURL(link.href); }
  return <section><div className="admin-guide"><strong>How to handle an enquiry:</strong> call the parent, use email when supplied, add your follow-up note, then change the status to Contacted, Enrolled, or Closed.</div><div className="admin-toolbar"><input aria-label="Search enquiries" placeholder="Search student, parent, phone or email" value={search} onChange={event => setSearch(event.target.value)} /><select aria-label="Filter by status" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="enrolled">Enrolled</option><option value="closed">Closed</option></select><button className="btn b3" onClick={exportCsv}>Export CSV</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student / request</th><th>Parent / reply</th><th>Status</th><th>Follow-up notes</th><th>Actions</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><strong>{item.studentName}</strong><br />{item.class}<br /><small>{item.school || 'School not provided'} · {item.subjects || 'Subjects not provided'}</small><p>{item.message || 'No message provided.'}</p></td><td><strong>{item.parentName}</strong><div className="reply-links"><a className="btn b2" href={`tel:${item.phone}`}>Call {item.phone}</a>{item.email && <a className="btn b2" href={`mailto:${item.email}?subject=Re: Brilliant Minds Tutorials enquiry`}>Email</a>}</div></td><td><select aria-label={`Status for ${item.studentName}`} value={item.status} onChange={event => update(item.id, { status: event.target.value })}><option value="new">New</option><option value="contacted">Contacted</option><option value="enrolled">Enrolled</option><option value="closed">Closed</option></select></td><td><input aria-label={`Notes for ${item.studentName}`} defaultValue={item.notes} placeholder="Add follow-up note" onBlur={event => update(item.id, { notes: event.target.value })} /></td><td><button className="danger" onClick={() => remove(item.id)}>Delete</button></td></tr>)}</tbody></table>{visible.length === 0 && <p>No enquiries match this filter.</p>}</div></section>;
}
