'use client';
import { useEffect, useState } from 'react';

type MediaItem = { id: string; name?: string; subject?: string; expertise?: string; bio?: string; caption?: string; category?: string; imageUrl: string; altText: string; published: boolean };
export default function MediaManager({ type }: { type: 'faculty' | 'gallery' }) {
  const [items, setItems] = useState<MediaItem[]>([]);
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);
  useEffect(() => { fetch(`/api/admin/media?type=${type}`, { cache: 'no-store' }).then(response => response.json()).then(setItems); }, [type]);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; setLoading(true); setMessage(''); const form = new FormData(formElement); form.set('type', type); const response = await fetch('/api/admin/media', { method: 'POST', body: form }); const body = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) { setMessage(body.error ?? 'Unable to save media.'); return; } setItems(current => [...current, body]); formElement.reset(); setMessage('Saved as unpublished. Publish it when the details are verified.'); }
  async function publish(item: MediaItem) { const nextPublished = !item.published; const response = await fetch('/api/admin/media', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ type, id: item.id, published: nextPublished }) }); if (response.ok) { setItems(current => current.map(entry => entry.id === item.id ? { ...entry, published: nextPublished } : entry)); setMessage(nextPublished ? 'Published. Refresh the public home page to see this item.' : 'Unpublished from the public site.'); } }
  async function remove(item: MediaItem) { if (!window.confirm('Delete this item permanently?')) return; const response = await fetch(`/api/admin/media?type=${type}&id=${encodeURIComponent(item.id)}`, { method: 'DELETE' }); if (response.ok) setItems(current => current.filter(entry => entry.id !== item.id)); }
  return <><form className="card media-form" onSubmit={save}><h2>Add {type === 'faculty' ? 'faculty' : 'gallery'} photo</h2><label>Image<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required /></label><label>Alt text<input name="altText" required maxLength={180} placeholder="Describe the image" /></label>{type === 'faculty' ? <><label>Name<input name="name" required maxLength={100} /></label><label>Subject<input name="subject" required maxLength={120} /></label><label>Expertise<input name="expertise" required maxLength={180} /></label><label>Bio<textarea name="bio" required maxLength={1000} /></label></> : <><label>Caption<input name="caption" required maxLength={180} /></label><label>Category<input name="category" required maxLength={80} /></label></>}<button className="btn b1" disabled={loading}>{loading ? 'Uploading…' : 'Upload and save'}</button>{message && <p role="status">{message}</p>}</form><div className="media-grid">{items.map(item => <article className="card media-item" key={item.id}><img src={item.imageUrl} alt={item.altText} loading="lazy" /><h3>{item.name ?? item.caption}</h3><p>{item.subject ?? item.category}</p><p>{item.published ? 'Published' : 'Unpublished'}</p><button className="btn b3" onClick={() => publish(item)}>{item.published ? 'Unpublish' : 'Publish'}</button> <button className="danger" onClick={() => remove(item)}>Delete</button></article>)}</div></>;
}
